### ISSUE TITLE
Spike: Determine the Libraries

### ISSUE THREAD

**Issue by mmislam101** [ihsan-project/ihsanReactNative#1]
Document why we make these decisions (especially over other libraries)

- Expo vs React native CLI
  - Consider CI system
  - Bilal: React native CLI. Easy to build it to the device. Continue working even disconnected, unlike Expo. 
  - Faraz: Expo is easy to setup for small projects. But other complicated projects that might need packages that expo doesn't cover. And expo apps are larger in memory.
  - **React Native CLI**
- Redux vs Context
  - Bilal: Redux and Redux Thunk. If in the future we see something that Redux has but Context doesn't have, it's easier to adopt it if we have redux.
  - Faraz: Prefer Contexts. But Redux is just better for large scale application
  - Mo: Have the redux and saga in the bootstrap so that there's an example of it
  - **Redux with Sagas** But loosely, absolutely not necessary if decide not to.
- Typescript vs JS
  - Bilal: typescript increases the package size. Flow is an alternative with smaller size, but drawback is there's a lot of definition.
  - Faraz: Just have any type-checked language. Doesn't think the bundled package will be that much larger between Typescript vs Flow. Big community around Typescript
  - **Typescript**
- Persistence?
  - Async Storage (probably SystemPreferences)
  - React does have SQLLite2 (Are any of these using the native CoreData and SQL)
  - Don't worry about this for the bootstrap. Just re-hydrate the app on restart
- MaterialUI vs ?
  - Bilal: Can just code it up directly. ReactNative Vector Icons
  - **Bootstrap will have MatrerialUI and ReactNative Vector Icons** But Khatmah might not be using it depending on Designs. https://www.npmjs.com/package/react-native-vector-icons
- Lint and Prettier, bootstrap off of Airbnb
  - Given with Typescript
- Network
  - **Axios**

Need to finish:
- Class based vs Functional (hooks)
- UI testing
  - Enzyme (web)
  - React Test Library (web)
  - (mobile?)
  - Research this more. Is there "Unit" UI testing for react components for react native.

**Comment by ahmednkhan24** [comment]
* Node version
* NPM vs Yarn

**Comment by ahmednkhan24** [comment]
My notes:

1. Node version
* Any LTS (Long Term Support) version. https://nodejs.org/en/about/releases/

2. NPM vs Yarn
* Originally Yarn was better than npm, but now they are very similar. Yarn still has better performance, albeit miniscule in the grand scheme of things.

3. Expo vs React-Native CLI
* In short: Expo is fast and easy install + setup, but larger app size with limitations, RNCLI takes a lot longer to install + setup with errors that are hard to debug, but has a smaller app size.
Expo is better for smaller projects that don’t require too many dependencies, RNCLI is better for everything else.

4. Redux vs Context
* Redux has a lot of boilerplate, but very powerful. Context is built into React and simple to setup, but isn’t the best when it comes to a large application that needs to share a lot of data throughout the app.

5. TypeScript vs JavaScript
* TypeScript has a larger learning curve than JS, but it provides compile-time type-checking that helps prevent silly bugs while also helping the debugging process.

6. Class-based vs Functional Components
* Functional components can now do everything class-based components can with less code using hooks. Modern React relies exclusively on functional components.

7. Unit Testing
* Enzyme is great, but react-testing-library provides a testing framework that is more human-centric.

**Comment by mmislam101** [comment]
@mmislam101 needs to take this and document it in the wiki
